[profile.default]
src = 'contracts'
test = 'foundry-test'
libs = ['lib', 'node_modules']
solc = '0.8.20'

[dependencies]
forge-std = { git = 'https://github.com/foundry-rs/forge-std', tag = 'v1.9.5' }
