[build]
  command = "cd apps/frontend && npm run build"
  publish = "apps/frontend/.next"

[build.environment]
  NODE_VERSION = "18"

# Netlify plugin for Next.js
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Redirects for SPA routing
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin","editor"]}

# Environment variables example
# [context.production.environment]
#   NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID = "your_wallet_connect_project_id"
#   NEXT_PUBLIC_APP_ENV = "production"

# [context.branch-deploy.environment]
#   NEXT_PUBLIC_APP_ENV = "staging"