version: "3.9"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: unykorn
      POSTGRES_PASSWORD: unykorn123
      POSTGRES_DB: compliance
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
