version: '3'
services:
  backend:
    image: node:18
    working_dir: /app
    command: ['node','dist/index.js']
    ports:
      - "3000:3000"
    volumes:
      - ../../apps/backend:/app
    depends_on:
      - db
  indexer:
    image: node:18
    working_dir: /app
    command: ['node','dist/index.js']
    volumes:
      - ../../apps/indexer:/app
    depends_on:
      - db
  agents:
    image: node:18
    working_dir: /app
    command: ['node','dist/index.js']
    volumes:
      - ../../apps/agents:/app
    depends_on:
      - db
  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  redis:
    image: redis:7
    ports:
      - "6379:6379"
