name: Feature request
description: Propose a feature or enhancement
labels: [enhancement]
body:
  - type: textarea
    id: need
    attributes:
      label: Problem / use case
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
