version: 2

run:
  timeout: 3m
  tests: true

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - ineffassign

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
