name: Auto Assign Issues

on:
  issues:
    types: [opened, reopened]

permissions:
  issues: write

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - name: Assign issue to kevanbtc
        uses: actions-ecosystem/action-add-assignees@v1
        with:
          assignees: kevanbtc
