name: Auto Assign

on:
  pull_request:
    types: [opened, reopened]

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - name: Auto assign reviewers
        uses: kentaro-m/auto-assign@v1.3.2
        with:
          assignees: 'kevanbtc'
          reviewers: 'kevanbtc'