name: Go ISO-bus

on:
  push:
    paths:
      - "go-bus/**"
      - ".github/workflows/go.yml"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: go-bus
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21.x"

      - name: Get deps
        run: go mod tidy

      - name: Build
        run: go build ./cmd/iso-bus

      - name: Vet
        run: go vet ./...

      - name: Test
        run: go test ./... -v
