name: Go Lint

on:
  push:
    paths:
      - "go-bus/**"
      - ".github/workflows/golangci.yml"
  pull_request:

jobs:
  golangci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: go-bus
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21.x"

      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60.3

      - name: Lint
        run: golangci-lint run ./...
