name: Security Audit

on: [push, pull_request]

jobs:
  slither-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip
          pip3 install slither-analyzer
      - name: Run Slither
        run: slither ./contracts
