name: Solidity (Foundry)

on:
  push:
    paths:
      - "src/**"
      - "script/**"
      - "test/**"
      - "foundry.toml"
      - ".github/workflows/solidity.yml"
  pull_request:

jobs:
  forge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: stable

      - name: Cache lib
        uses: actions/cache@v4
        with:
          path: lib
          key: ${{ runner.os }}-lib-${{ hashFiles('**/foundry.toml') }}
          restore-keys: |
            ${{ runner.os }}-lib-

      - name: Install deps
        run: |
          forge install OpenZeppelin/openzeppelin-contracts-upgradeable@v5.0.2 \
                       OpenZeppelin/openzeppelin-contracts@v5.0.2 \
                       foundry-rs/forge-std

      - name: Check formatting
        run: forge fmt --check

      - name: Build
        run: forge build

      - name: Test
        run: forge test -vv
