name: tests

on: [push, pull_request]

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install solc
        run: sudo apt-get update && sudo apt-get install -y solc
      - run: npm ci
      - name: Compile contracts
        run: npm run compile
      - name: Run tests
        run: npm test
